Repository fecgov/fec-eregs, pull requests merged in 2020-08, with the labels that each got.

#517 [MERGE WITH GITFLOW] Hotfix to fix the build errors caused by the python runtime version.
  runtime.txt
Labels: Bug

#519 Unpin python in runtime.txt
  runtime.txt
Labels: dependencies

#521 Fix formatting in tasks.py
  tasks.py
Labels: python
