Repository fecgov/fec-eregs, pull requests merged in 2024-03, with the labels that each got.

#837 [MERGE WITH GITFLOW] Release/public 20240305
  fec_eregs/static/fec_eregs/js/data/terms.json
Labels: Please review, release-branch

#838 upgrade django and cryptography
  fec_eregs/urls.py
  requirements-parsing.txt
  requirements.txt
Labels: Please review, Pipeline: Ready

#840 Feature/819 upgrade python v3.10
  .circleci/config.yml
  README.md
  requirements-parsing.txt
  runtime.txt
Labels: Please review

#844 [MERGE WITH GITFLOW] Release/public 20240318
  .circleci/config.yml
  README.md
  fec_eregs/urls.py
  requirements-parsing.txt
  requirements.txt
  runtime.txt
Labels: Please review, release-branch

#843 Update terms.json - Tech Modernization Updates
  fec_eregs/static/fec_eregs/js/data/terms.json
Labels: Please review
