Repository fecgov/fec-eregs, pull requests merged in 2024-02, with the labels that each got.

#828 upgrade cryptography
  requirements-parsing.txt
Labels: Please review

#827 [MERGE WITH GITFLOW] Release/public 20240206
  requirements-parsing.txt
  requirements.txt
Labels: release-branch

#829 migrate deploy to run in circleci
  .circleci/config.yml
Labels: Please review

#832 [MERGE WITH GITFLOW] Release/public 20240220
  .circleci/config.yml
  requirements-parsing.txt
Labels: Please review, release-branch

#834 Update terms.json add compensation #6120
  fec_eregs/static/fec_eregs/js/data/terms.json
Labels: Please review
